ga:
  num_generations: 100
  num_parents_mating: 2
  initial_population: 10
  crossover_probability: 0.3
  mutation_probability: 0.1
  termination:
    minimal_generations: 20
    epsilon: 1e-4
data:
  start_date: '2024-03-30'
  end_date: '2024-04-30'
  risk_rate: 4.5
  stocks:
    - AAPL
    - MSFT
    - GOOG
    - AMZN
    - TSLA
    - META
    - NVDA
    - NFLX
crossover: "arithmetic"
mutation: "gaussian"
objective: "sharpe"
selection: "best"
init: "dirichlet"
seed: 42
kind: "benchmark"
