ga:
  num_generations: 400
  num_parents_mating: 20
  initial_population: 100
  crossover_probability: 0.3
  mutation_probability: 0.05
  termination:
    minimal_generations: 40
    epsilon: 1e-4
data:
  start_date: '2024-03-30'
  end_date: '2024-04-30'
  risk_rate: 4.5
  stocks:
    - META
    - IBM
    - AAPL
    - MSFT
    - AMZN
    - NVDA
    - GOOGL
    - TSLA
    - NFLX
    - BABA
crossover: "convex_combination"
mutation: "directional"
objective: "sharpe"
selection: "top_k"
init: "dirichlet"
seed: 765
kind: "plot"
