ga:
  num_generations: 200
  num_parents_mating: 10
  initial_population: 100
  crossover_probability: 0.3
  mutation_probability: 0.05
  termination:
    minimal_generations: 10
    epsilon: 1e-2
data:
  start_date: '2024-03-30'
  end_date: '2024-04-30'
  risk_rate: 4.5
  stocks:
    - AAPL
    - MSFT
    - GOOG
crossover: "convex_combination"
mutation: "directional"
objective: "sharpe"
selection: "best"
init: "uniform"
seed: 42
